### ISSUE TITLE
Could you share the code that replicates the results of the MSNEA model?

### ISSUE THREAD

**Issue by sty945** [zjukg/MEAformer#3]
Hi friends,

I can't reproduce the results of the `MSNEA` model. Could you share the code that replicates the results of the `MSNEA` model?

**Comment by hackerchenzhuo** [comment]
@sty945 Yeah, I don't have feature data for this part either, not even image raw data. Therefore, we did not try to reproduce the results of the orig paper, but directly experimented on the features of VGG/ResNet from my dataset. To some extent, this is a fair comparison. 

Moreover, we are currently conducting model training on CLIP features, and we will  publish the content of this part within three months as soon as possible.
