### ISSUE TITLE
thank you for your work

### ISSUE THREAD

**Issue by MaoViolet** [zjukg/MEAformer#6]
Hello author, first of all thank you very much for your work, I would like to ask you about how long it takes to train the DBP15K dataset, you said in the literature that there is no parallelism, what should the batch_size be set to if only a single card 3090 is used, you provided 3000 in your code

**Comment by hackerchenzhuo** [comment]
Thank you for your interest in our work! Regarding your question about the training time for the DBP15K dataset without parallelism, it can vary based on several factors including the specific configuration and system capabilities.

For the batch size setting on a single 3090 card, I recommend starting with a batch size of 1000 and then gradually increasing it. It's a good practice to leave some room and not fully occupy the GPU memory as there can be some fluctuations during the training process. This approach will help you find a balance between performance and stability.
