### ISSUE TITLE
模型的test问题

### ISSUE THREAD

**Issue by MaoViolet** [zjukg/MEAformer#8]
您好，作者，首先非常感谢您的工作！！
我在代码训练最后一轮进行的test结果如下图所示，与论文中展示的数值差不多
![1XZN10OM$CWK1 Q9({A@L9N](https://github.com/user-attachments/assets/c3e71efa-23ed-4054-aef4-1bc2f4250f1a)
但是我将训练好的模型单独进行test的结果会有较大差异呢，下图是修改run_meaformer.sh文件中only_test=1，并在main.py中_load_model方法中加载训练好的模型，test的结果
![76$(ZJ)%@FNAM60LK)Q30K6](https://github.com/user-attachments/assets/16521d17-7b80-4ddc-9cfe-d4b47703414f)

请问一下作者，是我进行test的方法不对吗？

**Comment by hackerchenzhuo** [comment]
不好意思时间有点久我还真不太记得了，可能需要你debug一下，我之前自己跑的时候好像没出过这种问题

**Comment by MaoViolet** [comment]
感谢您的回答，我已经解决了这个问题
