### ISSUE TITLE
Multi-card training problem

### ISSUE THREAD

**Issue by ChenxiaoLiJoe** [zjukg/MEAformer#9]
Do you know if the code supports multi-card training? How to set the hyperparameters? Thanks.

**Comment by hackerchenzhuo** [comment]
Thank you for your question. Unfortunately, due to the underlying GNN algorithms used in the model, it does not support multi-card parallel training.

**Comment by ChenxiaoLiJoe** [comment]
Thank you for your reply!

**Comment by sheldonbb** [comment]
When I set _--model_name_ to _MCLEA, MSNEA, EVA_, the following error occurs:
Traceback (most recent call last): 
 File "main.py", line 532, in <module> 
  runner = Runner(cfgs, writer, logger, rank) 
 File "main.py", line 45, in __init__ 
  self.model_choise() 
 File "main.py", line 86, in model_choise 
  self.model = self._load_model(self.model, 
model_name=self.args.model_name_save) 
AttributeError: 'Runner' object has no attribute 'model'
